services:
  transfer_module:
    build:
      context: .
      dockerfile: Dockerfile
      secrets:
        - zivgitlab
    volumes: # define shared file-system and mount at default mount point for app
      - file_storage:/file_storage
    ports:
      - "8080:8080"
  swagger_ui: # use docker-image to serve swagger-ui: https://github.com/swagger-api/swagger-ui/blob/master/docs/usage/installation.md#docker
    build:
      context: .
      dockerfile: Dockerfile.swaggerui
      secrets:
        - zivgitlab
    ports:
      - "80:8080"
    environment:
      - BASE_URL=${BASE_URL}
      - SWAGGER_JSON=${SWAGGER_JSON}
  openssh-server:
    build:
      context: .
      dockerfile: Dockerfile.openssh
    container_name: openssh-server
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - PUBLIC_KEY=ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQC3KQA0uzazroFQAlmAyvH0mlsI/NTCWES3CNw8QFzQI1ZlMnefKdEZp1psmtVoQqMULSOWo1c76UaaD7pXGYzCHAAhLGaH8BCcOrCA1am0tookiFC7jWSroXW60qtf00ywhQ930efF62cNA+wwNSfluyVWUNpMZEAF5aa5pdliyegPt+QLBQEVRCaVlgnRBDN+ZIEanud653QP/HcxhojhpxwkB0K4NawM1lJPSKhd+VmbRwOSuupuxVonKRBEfe5Ilj7KfyFFB7VbRUQ+KvzeYplIY904LjC8Y4i8HaLo1BhNC5nUVFnggAtzkgrW/1n9socCuA2AMFRWHNmIiRM0gn0yOl18wKUCtdB/u/j6Lw6+d2cV3J97heUYd1RCGJrLjXOhyrY3B/OgIeslc2fy0OLkie7ElIckit8Bh0bBXU5jqgMniwgS4zAxIASPqGRa2wsvpTc/x6FVAk5cBuCyon/tjyquVrVOuIpGacZ3mRzHs3jhq3K25Nu59qmBoBM2PQIqAdD/esgyWyK6VEXa0X/KuQE6vqLIWwmIVrsc25hHtqrQgngicvdk/D4Vrmx3tQp/zd+bcNaCLU8F4B3tmN6YCIrcKsVY6bFtjijJ7xOdqn9nov7dhdPr78LJMEAAzyu5qaYjuw06QYBDYJ1T9vpXtvzzO2vnvftNznDuGw== root@d03891eee0b2
      - PASSWORD_ACCESS=true
      - USER_PASSWORD=pass
      - USER_NAME=foo
      - LOG_STDOUT=true
    volumes:
      - "$PWD/test_dcm_transfer_module/remote_storage:/remote_storage"
    ports:
      - 2222:2222
secrets:
  zivgitlab:
    file: ~/.netrc
volumes: # define docker volume
  file_storage:
